ECR changes for tie-bot
macmillanhighered/tie-bot pull request #14
Opened 2021-02-04 15:40 UTC by JonFranchi

yyyyyyyyeeeeeaaaahhhhhhhhhhhhhhhhh

2021-02-04 15:41 UTC, JonFranchi commented on Dockerfile
> -CMD echo 127.0.0.1  iam-local.mldev.cloud >> /etc/hosts;
It was underlined in red because its not allowed, and also this isn't IAM. bad copy pasta.

2021-02-04 15:42 UTC, JonFranchi commented on provision/docker-compose-swarm.yml
> +    image: ${TIE_BOT_IMAGE}
This was something I actually fixed 6 weeks ago and built to redeploy off a temp branch.  The deploy would no longer work.

2021-02-04 16:54 UTC, rick-hawley requested changes

2021-02-04 16:54 UTC, rick-hawley commented on README
> +
Major improvement!

2021-02-04 16:54 UTC, rick-hawley commented on Jenkinsfile
> +            def buildImage = docker.build("${dockerRepo}${app_name}:${dockerTag}")
`buildImage` variable is not used anymore, but we might want to repurpose it, as the string `{dockerRepo}${app_name}:${dockerTag}` is used 3 different times here (for the build, push, and serviceImage). Might cause a little less hassle in the future if someone decides to change it in the future but forgets to change it in all 3 places.

2021-02-04 18:32 UTC, JonFranchi commented on README
> +
I could swear I didn't do this, buuuuut....

2021-02-05 16:09 UTC, rick-hawley approved these changes

2021-02-08 15:27 UTC, merged